### ISSUE TITLE
Test cases for trip booking saga

### ISSUE THREAD

**Issue by hknoit** [berndruecker/trip-booking-saga-java#6]
I would like to use camunda in my project. I don't want to create workflows from bpmn diagrams but code only and I finally come to this repo. When it comes to testing the workflow, the approach in official doc is not working since it requires the bpmn diagram to deploy(??? i guess).   https://docs.camunda.org/manual/latest/user-guide/testing/                                                                                                                                          
   It would be nice if you can provide some test cases for the trip booking saga

**Comment by berndruecker** [comment]
Hi Manexwong. You can actually do the whole testing thing with coded workflows as well, you just have to deploy the workflow yourself via API using the Model API. I would love to add that test case, but most probably will not come to it any time soon. I leave the issue open till then as I agree it is agreat addition - and maybe somebody wants to jump in and contribute :-)

**Comment by berndruecker** [comment]
Added with https://github.com/berndruecker/trip-booking-saga-java/issues/9
