### ISSUE TITLE
Unable to run  TripBookingSaga.java 

### ISSUE THREAD

**Issue by sayom88** [berndruecker/trip-booking-saga-java#7]
Hello,
I have checkout the git repo and then planning to run  TripBookingSaga.java file.

For that I am planning to import the project into my Eclipse,but it seems I am unable to import the .zip file. Is there any extra setting that I need to do here?

![image](https://user-images.githubusercontent.com/16284729/86119479-28f0ab80-baf0-11ea-91a6-154623b5fc1c.png)

**Comment by berndruecker** [comment]
Please unzip the file on disk and then import an existing maven project - it is all maven based
